//библиотеки
@@include("../../node_modules/jquery/dist/jquery.min.js")
@@include("../../node_modules/select2/dist/js/select2.full.min.js")
@@include("../../node_modules/masonry-layout/dist/masonry.pkgd.js")
@@include("../../node_modules/@fancyapps/ui/dist/fancybox/fancybox.umd.js")
@@include("./libs/swiper-bundle.min.js")
@@include("./import/modules.js")
@@include("./import/components.js")
@@include("./import/main-script.js")
